/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "image_lines_t.h"

static int __image_lines_t_hash_computed;
static int64_t __image_lines_t_hash;

int64_t __image_lines_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __image_lines_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__image_lines_t_get_hash };
    (void) cp;

    int64_t hash = 0x7de03ac2a88830b8LL
         + __int64_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __line_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __circle_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __image_lines_t_get_hash(void)
{
    if (!__image_lines_t_hash_computed) {
        __image_lines_t_hash = __image_lines_t_hash_recursive(NULL);
        __image_lines_t_hash_computed = 1;
    }

    return __image_lines_t_hash;
}

int __image_lines_t_encode_array(void *buf, int offset, int maxlen, const image_lines_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].transmissionTimeStamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].imageTimeStamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].numLines), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __line_t_encode_array(buf, offset + pos, maxlen - pos, p[element].line, p[element].numLines);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].numCircles), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __circle_t_encode_array(buf, offset + pos, maxlen - pos, p[element].circle, p[element].numCircles);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].rawIplData, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].imageSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].imageData, p[element].imageSize);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int image_lines_t_encode(void *buf, int offset, int maxlen, const image_lines_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __image_lines_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __image_lines_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __image_lines_t_encoded_array_size(const image_lines_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].transmissionTimeStamp), 1);

        size += __int64_t_encoded_array_size(&(p[element].imageTimeStamp), 1);

        size += __int16_t_encoded_array_size(&(p[element].numLines), 1);

        size += __line_t_encoded_array_size(p[element].line, p[element].numLines);

        size += __int16_t_encoded_array_size(&(p[element].numCircles), 1);

        size += __circle_t_encoded_array_size(p[element].circle, p[element].numCircles);

        size += __int32_t_encoded_array_size(&(p[element].nSize), 1);

        size += __int8_t_encoded_array_size(p[element].rawIplData, p[element].nSize);

        size += __int32_t_encoded_array_size(&(p[element].imageSize), 1);

        size += __int8_t_encoded_array_size(p[element].imageData, p[element].imageSize);

    }
    return size;
}

int image_lines_t_encoded_size(const image_lines_t *p)
{
    return 8 + __image_lines_t_encoded_array_size(p, 1);
}

int __image_lines_t_decode_array(const void *buf, int offset, int maxlen, image_lines_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].transmissionTimeStamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].imageTimeStamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].numLines), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].line = (line_t*) lcm_malloc(sizeof(line_t) * p[element].numLines);
        thislen = __line_t_decode_array(buf, offset + pos, maxlen - pos, p[element].line, p[element].numLines);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].numCircles), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].circle = (circle_t*) lcm_malloc(sizeof(circle_t) * p[element].numCircles);
        thislen = __circle_t_decode_array(buf, offset + pos, maxlen - pos, p[element].circle, p[element].numCircles);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].rawIplData = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].nSize);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].rawIplData, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].imageSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].imageData = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].imageSize);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].imageData, p[element].imageSize);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __image_lines_t_decode_array_cleanup(image_lines_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].transmissionTimeStamp), 1);

        __int64_t_decode_array_cleanup(&(p[element].imageTimeStamp), 1);

        __int16_t_decode_array_cleanup(&(p[element].numLines), 1);

        __line_t_decode_array_cleanup(p[element].line, p[element].numLines);
        if (p[element].line) free(p[element].line);

        __int16_t_decode_array_cleanup(&(p[element].numCircles), 1);

        __circle_t_decode_array_cleanup(p[element].circle, p[element].numCircles);
        if (p[element].circle) free(p[element].circle);

        __int32_t_decode_array_cleanup(&(p[element].nSize), 1);

        __int8_t_decode_array_cleanup(p[element].rawIplData, p[element].nSize);
        if (p[element].rawIplData) free(p[element].rawIplData);

        __int32_t_decode_array_cleanup(&(p[element].imageSize), 1);

        __int8_t_decode_array_cleanup(p[element].imageData, p[element].imageSize);
        if (p[element].imageData) free(p[element].imageData);

    }
    return 0;
}

int image_lines_t_decode(const void *buf, int offset, int maxlen, image_lines_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __image_lines_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __image_lines_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int image_lines_t_decode_cleanup(image_lines_t *p)
{
    return __image_lines_t_decode_array_cleanup(p, 1);
}

int __image_lines_t_clone_array(const image_lines_t *p, image_lines_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].transmissionTimeStamp), &(q[element].transmissionTimeStamp), 1);

        __int64_t_clone_array(&(p[element].imageTimeStamp), &(q[element].imageTimeStamp), 1);

        __int16_t_clone_array(&(p[element].numLines), &(q[element].numLines), 1);

        q[element].line = (line_t*) lcm_malloc(sizeof(line_t) * q[element].numLines);
        __line_t_clone_array(p[element].line, q[element].line, p[element].numLines);

        __int16_t_clone_array(&(p[element].numCircles), &(q[element].numCircles), 1);

        q[element].circle = (circle_t*) lcm_malloc(sizeof(circle_t) * q[element].numCircles);
        __circle_t_clone_array(p[element].circle, q[element].circle, p[element].numCircles);

        __int32_t_clone_array(&(p[element].nSize), &(q[element].nSize), 1);

        q[element].rawIplData = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].nSize);
        __int8_t_clone_array(p[element].rawIplData, q[element].rawIplData, p[element].nSize);

        __int32_t_clone_array(&(p[element].imageSize), &(q[element].imageSize), 1);

        q[element].imageData = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].imageSize);
        __int8_t_clone_array(p[element].imageData, q[element].imageData, p[element].imageSize);

    }
    return 0;
}

image_lines_t *image_lines_t_copy(const image_lines_t *p)
{
    image_lines_t *q = (image_lines_t*) malloc(sizeof(image_lines_t));
    __image_lines_t_clone_array(p, q, 1);
    return q;
}

void image_lines_t_destroy(image_lines_t *p)
{
    __image_lines_t_decode_array_cleanup(p, 1);
    free(p);
}

int image_lines_t_publish(lcm_t *lc, const char *channel, const image_lines_t *p)
{
      int max_data_size = image_lines_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = image_lines_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _image_lines_t_subscription_t {
    image_lines_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void image_lines_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    image_lines_t p;
    memset(&p, 0, sizeof(image_lines_t));
    status = image_lines_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding image_lines_t!!!\n", status);
        return;
    }

    image_lines_t_subscription_t *h = (image_lines_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    image_lines_t_decode_cleanup (&p);
}

image_lines_t_subscription_t* image_lines_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    image_lines_t_handler_t f, void *userdata)
{
    image_lines_t_subscription_t *n = (image_lines_t_subscription_t*)
                       malloc(sizeof(image_lines_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 image_lines_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg image_lines_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int image_lines_t_subscription_set_queue_capacity (image_lines_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int image_lines_t_unsubscribe(lcm_t *lcm, image_lines_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe image_lines_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

