/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _image_lines_t_h
#define _image_lines_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "line_t.h"
#include "circle_t.h"
typedef struct _image_lines_t image_lines_t;
struct _image_lines_t
{
    int64_t    transmissionTimeStamp;
    int64_t    imageTimeStamp;
    int16_t    numLines;
    line_t     *line;
    int16_t    numCircles;
    circle_t   *circle;
};

image_lines_t   *image_lines_t_copy(const image_lines_t *p);
void image_lines_t_destroy(image_lines_t *p);

typedef struct _image_lines_t_subscription_t image_lines_t_subscription_t;
typedef void(*image_lines_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const image_lines_t *msg, void *user);

int image_lines_t_publish(lcm_t *lcm, const char *channel, const image_lines_t *p);
image_lines_t_subscription_t* image_lines_t_subscribe(lcm_t *lcm, const char *channel, image_lines_t_handler_t f, void *userdata);
int image_lines_t_unsubscribe(lcm_t *lcm, image_lines_t_subscription_t* hid);
int image_lines_t_subscription_set_queue_capacity(image_lines_t_subscription_t* subs,
                              int num_messages);


int  image_lines_t_encode(void *buf, int offset, int maxlen, const image_lines_t *p);
int  image_lines_t_decode(const void *buf, int offset, int maxlen, image_lines_t *p);
int  image_lines_t_decode_cleanup(image_lines_t *p);
int  image_lines_t_encoded_size(const image_lines_t *p);

// LCM support functions. Users should not call these
int64_t __image_lines_t_get_hash(void);
int64_t __image_lines_t_hash_recursive(const __lcm_hash_ptr *p);
int     __image_lines_t_encode_array(void *buf, int offset, int maxlen, const image_lines_t *p, int elements);
int     __image_lines_t_decode_array(const void *buf, int offset, int maxlen, image_lines_t *p, int elements);
int     __image_lines_t_decode_array_cleanup(image_lines_t *p, int elements);
int     __image_lines_t_encoded_array_size(const image_lines_t *p, int elements);
int     __image_lines_t_clone_array(const image_lines_t *p, image_lines_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
