/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _point_t_h
#define _point_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _point_t point_t;
struct _point_t
{
    int8_t     x;
    int8_t     y;
};

point_t   *point_t_copy(const point_t *p);
void point_t_destroy(point_t *p);

typedef struct _point_t_subscription_t point_t_subscription_t;
typedef void(*point_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const point_t *msg, void *user);

int point_t_publish(lcm_t *lcm, const char *channel, const point_t *p);
point_t_subscription_t* point_t_subscribe(lcm_t *lcm, const char *channel, point_t_handler_t f, void *userdata);
int point_t_unsubscribe(lcm_t *lcm, point_t_subscription_t* hid);
int point_t_subscription_set_queue_capacity(point_t_subscription_t* subs,
                              int num_messages);


int  point_t_encode(void *buf, int offset, int maxlen, const point_t *p);
int  point_t_decode(const void *buf, int offset, int maxlen, point_t *p);
int  point_t_decode_cleanup(point_t *p);
int  point_t_encoded_size(const point_t *p);

// LCM support functions. Users should not call these
int64_t __point_t_get_hash(void);
int64_t __point_t_hash_recursive(const __lcm_hash_ptr *p);
int     __point_t_encode_array(void *buf, int offset, int maxlen, const point_t *p, int elements);
int     __point_t_decode_array(const void *buf, int offset, int maxlen, point_t *p, int elements);
int     __point_t_decode_array_cleanup(point_t *p, int elements);
int     __point_t_encoded_array_size(const point_t *p, int elements);
int     __point_t_clone_array(const point_t *p, point_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
