/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "point_t.h"

static int __point_t_hash_computed;
static int64_t __point_t_hash;

int64_t __point_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __point_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__point_t_get_hash;
    (void) cp;

    int64_t hash = 0xabddc706ad074f64LL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __point_t_get_hash(void)
{
    if (!__point_t_hash_computed) {
        __point_t_hash = __point_t_hash_recursive(NULL);
        __point_t_hash_computed = 1;
    }

    return __point_t_hash;
}

int __point_t_encode_array(void *buf, int offset, int maxlen, const point_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int point_t_encode(void *buf, int offset, int maxlen, const point_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __point_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __point_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __point_t_encoded_array_size(const point_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].x), 1);

        size += __int16_t_encoded_array_size(&(p[element].y), 1);

    }
    return size;
}

int point_t_encoded_size(const point_t *p)
{
    return 8 + __point_t_encoded_array_size(p, 1);
}

int __point_t_decode_array(const void *buf, int offset, int maxlen, point_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __point_t_decode_array_cleanup(point_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].x), 1);

        __int16_t_decode_array_cleanup(&(p[element].y), 1);

    }
    return 0;
}

int point_t_decode(const void *buf, int offset, int maxlen, point_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __point_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __point_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int point_t_decode_cleanup(point_t *p)
{
    return __point_t_decode_array_cleanup(p, 1);
}

int __point_t_clone_array(const point_t *p, point_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].x), &(q[element].x), 1);

        __int16_t_clone_array(&(p[element].y), &(q[element].y), 1);

    }
    return 0;
}

point_t *point_t_copy(const point_t *p)
{
    point_t *q = (point_t*) malloc(sizeof(point_t));
    __point_t_clone_array(p, q, 1);
    return q;
}

void point_t_destroy(point_t *p)
{
    __point_t_decode_array_cleanup(p, 1);
    free(p);
}

int point_t_publish(lcm_t *lc, const char *channel, const point_t *p)
{
      int max_data_size = point_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = point_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _point_t_subscription_t {
    point_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void point_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    point_t p;
    memset(&p, 0, sizeof(point_t));
    status = point_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding point_t!!!\n", status);
        return;
    }

    point_t_subscription_t *h = (point_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    point_t_decode_cleanup (&p);
}

point_t_subscription_t* point_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    point_t_handler_t f, void *userdata)
{
    point_t_subscription_t *n = (point_t_subscription_t*)
                       malloc(sizeof(point_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 point_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg point_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int point_t_subscription_set_queue_capacity (point_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int point_t_unsubscribe(lcm_t *lcm, point_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe point_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

